// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dbpayments

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Payment struct {
	Correlationid uuid.UUID
	Amount        pgtype.Numeric
	RequestedAt   time.Time
	Api           int32
}
